# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Test

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  Build:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        env:
          DOTNET_INSTALL_DIR: "./.dotnet"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  Test:
    runs-on: [self-hosted, linux]

    needs: Build

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x
          env:
            DOTNET_INSTALL_DIR: "./.dotnet"

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --no-restore

        - name: Test
          run: dotnet test --no-build --verbosity normal