# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

on:
  workflow_call:

jobs:
  Build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        env:
          DOTNET_INSTALL_DIR: "./.dotnet"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore